[package]
name = "qr-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
autobins = false

[dependencies]
qr-core.workspace = true
qr-render.workspace = true
wasm-bindgen.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test.workspace = true
