[package]
name = "qr-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "qr-web"
path = "src/main.rs"

[dependencies]
leptos.workspace = true
qr-core.workspace = true
qr-render.workspace = true
web-sys = { workspace = true, features = ["ClipboardEvent", "DataTransfer", "DragEvent", "Event", "HtmlTextAreaElement", "InputEvent"] }
