use std::error::Error;

use qr_core::tables::ErrorCorrection;
use qr_core::{EncodeRequest, Version, encode};
use qr_render::{LogoStyle, ProfileId, RenderModel, RenderOptions, SUPPORTED_PROFILES};

fn main() -> Result<(), Box<dyn Error>> {
    println!("# Bundled logo placement policy\n");
    println!("## Agent metadata\n");
    println!("- **Purpose:** generated exhaustive logo-placement evidence.");
    println!(
        "- **Read when:** changing logo geometry, profile/version limits, or approved branding."
    );
    println!("- **Authority:** generated observations from current qr-core/qr-render code.");
    println!(
        "- **Mutation rule:** do not edit this file; change the generator and regenerate it.\n"
    );
    println!(
        "Generated by `cargo run -p qr-render --example logo_policy`. Every approved fixed variant retains exact Version 6 centering and records typed rejection for other versions.\n"
    );
    println!(
        "| Profile | H version | Matrix | PNG module scale | Source logo bounds (modules ×10000) | Knockout bounds (modules) | Protected clearance | Obscured data | Obscured remainder | Outcome |"
    );
    println!("|---|---:|---:|---:|---|---|---:|---:|---:|---|");
    for profile in SUPPORTED_PROFILES {
        for version_number in
            profile.minimum_version().number()..=profile.maximum_version().number()
        {
            let text = payload_for_high_version(version_number)?;
            let encoded = encode(EncodeRequest::first_fit(
                &text,
                ErrorCorrection::High,
                Version::try_from(version_number)?,
            ))?;
            let options = RenderOptions::safe(profile)?.with_logo(LogoStyle::Bundled)?;
            let Ok(model) = RenderModel::new(&encoded, options) else {
                println!(
                    "| {} | {} | {}×{} | — | — | — | — | — | — | no approved function-safe geometry |",
                    profile_name(profile.id()),
                    version_number,
                    encoded.modules().size(),
                    encoded.modules().size(),
                );
                continue;
            };
            let logo = model.logo_placement().ok_or("logo policy rejected a row")?;
            let source = logo.source_bounds();
            let knockout = logo.knockout_bounds();
            println!(
                "| {} | {} | {}×{} | {} px | ({}, {}) {}×{} | ({}, {}) {}×{} | {} modules | {} | {} | valid |",
                profile_name(profile.id()),
                version_number,
                encoded.modules().size(),
                encoded.modules().size(),
                model.png_placement().module_scale().get(),
                source.left_ten_thousandths(),
                source.top_ten_thousandths(),
                source.width_ten_thousandths(),
                source.height_ten_thousandths(),
                knockout.left().get(),
                knockout.top().get(),
                knockout.width().get(),
                knockout.height().get(),
                logo.protected_clearance(),
                logo.obscured_data_modules(),
                logo.obscured_remainder_modules(),
            );
        }
    }
    Ok(())
}

const fn profile_name(profile: ProfileId) -> &'static str {
    match profile {
        ProfileId::Small => "Small",
        ProfileId::Standard => "Standard",
        ProfileId::PrimaryCta => "Primary CTA",
        ProfileId::HeroCampaign => "Hero / Campaign",
        ProfileId::BusinessCard => "Business card",
        ProfileId::FlyerBrochure => "Flyer / Brochure",
        ProfileId::PosterPackage => "Poster / Package",
    }
}

fn payload_for_high_version(version: u8) -> Result<String, Box<dyn Error>> {
    let maximum_version = Version::try_from(version)?;
    let (mut lower, mut upper) = (1_usize, 4_096_usize);
    while lower <= upper {
        let length = lower + (upper - lower) / 2;
        let text = "a".repeat(length);
        match encode(EncodeRequest::first_fit(
            &text,
            ErrorCorrection::High,
            maximum_version,
        )) {
            Ok(encoded) if encoded.version().number() == version => return Ok(text),
            Ok(_) => lower = length + 1,
            Err(_) => {
                let Some(previous) = length.checked_sub(1) else {
                    break;
                };
                upper = previous;
            }
        }
    }
    Err(format!("no byte payload selected H-level version {version}").into())
}
