use std::error::Error;

use qr_core::tables::ErrorCorrection;
use qr_core::{EncodeRequest, Version, encode};
use qr_render::{LogoStyle, RenderModel, RenderOptions, SUPPORTED_PROFILES};

fn main() -> Result<(), Box<dyn Error>> {
    println!("# Bundled logo placement policy\n");
    println!(
        "Generated by `cargo run -p qr-render --example logo_policy`. Logo artwork is accepted only when its exact matrix-centered placement is function-safe.\n"
    );
    println!(
        "| Profile | H version | Matrix | PNG module scale | Source logo bounds (modules ×10000) | Knockout bounds (modules) | Protected clearance | Obscured data | Obscured remainder | Outcome |"
    );
    println!("|---|---:|---:|---:|---|---|---:|---:|---:|---|");
    for profile in SUPPORTED_PROFILES {
        for version_number in 1..=profile.maximum_version().number() {
            let text = payload_for_high_version(version_number)?;
            let encoded = encode(EncodeRequest::first_fit(
                &text,
                ErrorCorrection::High,
                Version::try_from(version_number)?,
            ))?;
            let options = RenderOptions::safe(profile)?.with_logo(LogoStyle::Bundled)?;
            let Ok(model) = RenderModel::new(&encoded, options) else {
                println!(
                    "| {:?} | {} | {}×{} | — | — | — | — | — | — | unsafe centered geometry |",
                    profile.id(),
                    version_number,
                    encoded.modules().size(),
                    encoded.modules().size(),
                );
                continue;
            };
            let logo = model.logo_placement().ok_or("logo policy rejected a row")?;
            let source = logo.source_bounds();
            let knockout = logo.knockout_bounds();
            println!(
                "| {:?} | {} | {}×{} | {} px | ({}, {}) {}×{} | ({}, {}) {}×{} | {} modules | {} | {} | valid |",
                profile.id(),
                version_number,
                encoded.modules().size(),
                encoded.modules().size(),
                model.png_placement().module_scale().get(),
                source.left_ten_thousandths(),
                source.top_ten_thousandths(),
                source.width_ten_thousandths(),
                source.height_ten_thousandths(),
                knockout.left().get(),
                knockout.top().get(),
                knockout.width().get(),
                knockout.height().get(),
                logo.protected_clearance(),
                logo.obscured_data_modules(),
                logo.obscured_remainder_modules(),
            );
        }
    }
    Ok(())
}

fn payload_for_high_version(version: u8) -> Result<String, Box<dyn Error>> {
    for length in 1..=1_000 {
        let text = "a".repeat(length);
        if encode(EncodeRequest::first_fit(
            &text,
            ErrorCorrection::High,
            Version::try_from(version)?,
        ))
        .is_ok_and(|encoded| encoded.version().number() == version)
        {
            return Ok(text);
        }
    }
    Err(format!("no byte payload selected H-level version {version}").into())
}
